language: go

go:
  - 1.15

sudo: required

services:
  - docker
  - redis-server

before_script:
  - make run-containers
  - sleep 10

script:
  - make test

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile coverage-all.out -service=travis-ci
  - make cross-linux
  - ./push_to_docker.sh
