[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.1"

[[constraint]]
  name = "github.com/newrelic/go-agent"
  version = "1.9.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/valyala/fasthttp"
  version = "20160617.0.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.0.5"

[[constraint]]
  name = "github.com/topfreegames/extensions"
  version = "5.7.0"

[prune]
  go-tests = true
  unused-packages = true
