version: '3'
services:
  emqtt:
    image: tfgco/emq-docker:v2.3-tfg-beta10
    environment:
      - EMQ_LISTENER__API__MGMT=0.0.0.0:8080
    ports:
      - "1883:1883"
      - "8080:8080"
    healthcheck:
      test: "nc -z 0.0.0.0 8080"
      interval: 30s
      timeout: 30s
      retries: 3
  redis:
    image: redis:3.2
    ports:
      - "4444:6379"
