healthcheck:
  workingText: "WORKING"
mqttserver:
  host: localhost
  port: 1883
  user: mqttclient
  pass: password
  usetls: false
  insecure_tls: true
redis:
  host: localhost
  port: 4444
  password: ""
  maxPoolSize: 20
newrelic:
  key: ""
sentry:
  url: ""
jaeger:
  disabled: true
  samplingProbability: 0.001
