mqttserver:
  host: localhost
  port: 1883
  user: mqttclient
  pass: password
  usetls: false
  insecure_tls: true
redis:
  host: localhost
  port: 4444
  maxPoolSize: 20
jaeger:
  disabled: false
  samplingProbability: 1.0
